image: gitpod/workspace-full-vnc

tasks:
- name: SETUP - PYTHON ENVIRONMENT
  init: |
    wget "https://github.com/marbl/ModDotPlot/archive/refs/tags/v0.8.7.zip"
    unzip v*.zip

    cd ModDotPlot-0.8.7
    python -m venv venv
    source venv/bin/activate
    python -m pip install .
    clear

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public

workspaceLocation: "/workspace"
